language: python
python:
    - "2.7"
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy python-scipy
install: pip install --use-mirrors --no-deps -r requirements-build.txt
script: nosetests
