language: python
python:
    - "2.7"
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
    - pip install -r requirements.txt --use-mirrors
script: nosetests
